<?php

########################################################################
# Extension Manager/Repository config file for ext: "dl_accounting"
#
# Auto generated by Extension Builder 2012-03-25
#
# Manual updates:
# Only the data in the array - anything else is removed by next write.
# "version" and "dependencies" must not be touched!
########################################################################

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Accounting module',
	'description' => 'Accounting module for DPSG Freiburg',
	'category' => 'plugin',
	'author' => 'Daniel Lienert',
	'author_email' => 'daniel@lienert.cc',
	'author_company' => 'Daniel Lienert',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '',
	'constraints' => array(
		'depends' => array(
			'extbase' => '1.3.0',
			'fluid' => '1.3.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>